### ISSUE TITLE
System.NullReferenceException while refreshing projects

### ISSUE THREAD

**Issue by avishnyakov** [onlyutkarsh/AppVeyorExtension#3]
Configured API token, refreshed the project and got the following errors:

```
TimeStamp:10/11/2015 11:59:24 AM
Message:Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AppVeyor.UI.Common.ProjectComparer.Equals(Project first, Project second)
   at AppVeyor.Common.Extensions.EnumerableExtensions.ListEqual[T](ObservableCollection`1 first, ObservableCollection`1 second, IEqualityComparer`1 comparer)
   at AppVeyor.UI.ViewModel.AppVeyorWindowViewModel.c.h()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AppVeyor.UI.ViewModel.AppVeyorWindowViewModel.f.d()
```

**Comment by onlyutkarsh** [comment]
@avishnyakov thanks for reporting this. We are aware of this defect, and is mainly to do with async operations we do. Hope to fix this soon.

**Comment by floydchenv** [comment]
I also experience this problem, but my VS direct crashed.
